server:
  port: 9191

spring:
  cloud:
    consul:
      host: consul-container
      port: 8500
      discovery:
        register: true

    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
            
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/departments/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
